"""add image_url to products

Revision ID: 726fd28f8641
Revises: 
Create Date: 2026-06-03 13:48:32.723657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726fd28f8641'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
